### ISSUE TITLE
Please update to support 2022.3

### ISSUE THREAD

**Issue by rostislaved** [ADMARIl/halcyon-jetbrains#24]
And could you please give a link on a manual how to do it? Maybe some jetbrains help pages

**Comment by peterycky** [comment]
@ADMARIl or anyone with write access, could you take a peek at this PR?

**Comment by digeomel** [comment]
I just updated. Looks like something is wrong, this is the stacktrace from IntelliJ:

```
com.intellij.diagnostic.PluginException: Cannot create extension (class=com.ADMARIl.halcyonjetbrains.HandleStartup.StartupWelcomeActivity) [Plugin: com.ADMARIl.halcyon-jetbrains]
	at com.intellij.serviceContainer.ComponentManagerImpl.createError(ComponentManagerImpl.kt:1051)
	at com.intellij.openapi.extensions.impl.XmlExtensionAdapter.doCreateInstance(XmlExtensionAdapter.kt:70)
	at com.intellij.openapi.extensions.impl.XmlExtensionAdapter.createInstance(XmlExtensionAdapter.kt:31)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runPostStartupActivities(StartupManagerImpl.kt:587)
	at com.intellij.ide.startup.impl.StartupManagerImpl.access$runPostStartupActivities(StartupManagerImpl.kt:66)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runStartupActivities$2.invokeSuspend(StartupManagerImpl.kt:184)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: com.intellij.diagnostic.PluginException: Cannot load class com.ADMARIl.halcyonjetbrains.HandleStartup.StartupWelcomeActivity (
  error: com/ADMARIl/halcyonjetbrains/HandleStartup/StartupWelcomeActivity has been compiled by a more recent version of the Java Runtime (class file version 63.0), this version of the Java Runtime only recognizes class file versions up to 61.0,
  classLoader=PluginClassLoader(plugin=PluginDescriptor(name=Halcyon Theme, id=com.ADMARIl.halcyon-jetbrains, descriptorPath=plugin.xml, path=~/.local/share/JetBrains/IntelliJIdea2022.3/halcyon-jetbrains, version=2.3.0, package=null, isBundled=false), packagePrefix=null, instanceId=14, state=active)
)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:428)
	at com.intellij.ide.plugins.cl.PluginClassLoader.tryLoadingClass(PluginClassLoader.java:242)
	at com.intellij.serviceContainer.ComponentManagerImplKt.doLoadClass(ComponentManagerImpl.kt:1519)
	at com.intellij.serviceContainer.ComponentManagerImplKt.access$doLoadClass(ComponentManagerImpl.kt:1)
	at com.intellij.serviceContainer.ComponentManagerImpl.loadClass(ComponentManagerImpl.kt:941)
	at com.intellij.openapi.extensions.impl.InterfaceExtensionImplementationClassResolver.resolveImplementationClass(InterfaceExtensionImplementationClassResolver.kt:24)
	at com.intellij.openapi.extensions.impl.XmlExtensionAdapter.doCreateInstance(XmlExtensionAdapter.kt:49)
	... 10 more
Caused by: java.lang.UnsupportedClassVersionError: com/ADMARIl/halcyonjetbrains/HandleStartup/StartupWelcomeActivity has been compiled by a more recent version of the Java Runtime (class file version 63.0), this version of the Java Runtime only recognizes class file versions up to 61.0
	at java.base/java.lang.ClassLoader.defineClass2(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1103)
	at com.intellij.util.lang.UrlClassLoader.consumeClassData(UrlClassLoader.java:264)
	at com.intellij.util.lang.ZipResourceFile.findClass(ZipResourceFile.java:113)
	at com.intellij.util.lang.JarLoader.findClass(JarLoader.java:63)
	at com.intellij.util.lang.ClassPath.findClassInLoader(ClassPath.java:243)
	at com.intellij.util.lang.ClassPath.findClass(ClassPath.java:176)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:420)
	... 16 more

```

**Comment by halcyonCorsair** [comment]
I am also seeing the same issues with 2022.3.2.

**Comment by ADMARIl** [comment]
hmmm guess I was foiled by trying to build at the bleeding edge. I'll take a look

**Comment by ADMARIl** [comment]
Seems the issue was that I was building the plugin using jdk 19. Downgrading to 17 seems to have fixed it. New release has been sent of to jetbrains so it should be public in a few days.
